# Usando una imagen oficial de ubuntu
FROM ubuntu:20.04

# Seteando variables de entorno
ENV APP_NAME="Mi Primera App de Dia 1" \
    APP_VERSION="1.0"

# Corriendo algunos comandos y actualizando dependencias
RUN apt-get update && \
    apt-get install -y \
    python3 \
    python3-pip

# Creando una carpeta
WORKDIR /app

# Copiando el contenido actual en esa carpeta
COPY . /app

# Instalando cualquier dependencia adicional usando pip (opcional)
# RUN pip3 install -r requirements.txt

# Especificando el entrypoint del docker container
CMD ["python3", "app.py"]
