apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  namespace: victor
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: victor-container
        image: us-docker.pkg.dev/google-samples/containers/gke/gb-frontend:v5